FROM ubuntu:20.04

WORKDIR /app/yocto
WORKDIR /app/task

ENV TZ=Asia/Shanghai DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get -y install apt-transport-https && apt-get -y install ca-certificates

RUN echo "deb https://mirrors.ustc.edu.cn/ubuntu/ focal main restricted universe multiverse" > /etc/apt/sources.list && \
    echo "deb https://mirrors.ustc.edu.cn/ubuntu/ focal-security main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb https://mirrors.ustc.edu.cn/ubuntu/ focal-updates main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb https://mirrors.ustc.edu.cn/ubuntu/ focal-backports main restricted universe multiverse" >> /etc/apt/sources.list

RUN apt-get update 
RUN apt-get install -y tzdata locales
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    echo 'LANG="en_US.UTF-8"'>/etc/default/locale && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8

ENV LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8

RUN apt-get update && apt-get install -y gawk wget git diffstat unzip texinfo gcc build-essential \
    chrpath socat cpio python python3 python3-pip python3-pexpect xz-utils debianutils \
    iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev pylint3 \
    xterm python3-subunit mesa-common-dev zstd liblz4-tool libpq-dev python3-dev musl-dev

COPY ./src/requirements.txt .
RUN pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt

RUN groupadd -g 1000 dianshao && useradd -r -u 1000 -g dianshao dianshao && \
    chown -R dianshao:dianshao /app/yocto && chown -R dianshao:dianshao /app/task

COPY --chown=1000:1000 ./src /app/task
USER dianshao