# Generated by Django 2.2 on 2021-12-13 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MyPackages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('bbappend', 'bbappend'), ('bb', 'bb')], max_length=10)),
                ('version', models.CharField(max_length=100)),
                ('license', models.CharField(max_length=100)),
                ('lic_files_chksum', models.CharField(max_length=150)),
                ('depends', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
                ('section', models.CharField(max_length=50)),
                ('src_url', models.CharField(max_length=50)),
                ('src_url_md5', models.CharField(max_length=200)),
                ('src_url_sha256', models.CharField(max_length=200)),
                ('local_files', models.CharField(max_length=200)),
                ('files_install_directory', models.CharField(max_length=60)),
                ('building_directory', models.CharField(max_length=100)),
                ('inherit', models.CharField(max_length=60)),
                ('systemd_service_pn', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_path', models.CharField(max_length=150)),
                ('project_version', models.CharField(choices=[('ZEUS', 'zeus'), ('GATESGARTH', 'gatesgarth'), ('DUNFELL', 'dunfell'), ('HARDKNOTT', 'hardknott')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('do_configure', 'Configure'), ('do_compile', 'Compile'), ('do_install', 'Install')], max_length=60)),
                ('subtype', models.CharField(choices=[('prepend', 'Prepend'), ('none', 'None'), ('append', 'Append')], max_length=60)),
                ('op', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=150)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.MyPackages')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meta_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.MetaLayer')),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Recipes')),
            ],
        ),
        migrations.AddField(
            model_name='mypackages',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.CreateModel(
            name='MyConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=150)),
                ('strength', models.CharField(choices=[('normal', 'normal'), ('weak', 'weak'), ('very weak', 'very weak'), ('append', 'append')], max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.AddField(
            model_name='metalayer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=100)),
                ('command', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
