# Generated by Django 2.2 on 2021-12-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='op',
            field=models.CharField(max_length=300),
        ),
    ]
