# Generated by Django 2.2 on 2021-12-13 10:55

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20211213_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=30)),
                ('path', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.MyPackages')),
            ],
        ),
    ]
