# Generated by Django 2.2 on 2021-12-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_localfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localfile',
            name='content',
        ),
    ]
