# Generated by Django 2.2 on 2021-12-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_localfile_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localfile',
            name='content',
            field=models.CharField(max_length=2000),
        ),
    ]
