# Generated by Django 2.2 on 2021-12-14 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20211214_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypackages',
            name='src_rev',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
