# Generated by Django 2.2 on 2021-12-22 03:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_mypackages_src_rev'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypackages',
            name='donwload_method',
            field=models.CharField(choices=[('git', 'git'), ('wget', 'wget')], default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypackages',
            name='initial_method',
            field=models.CharField(choices=[('Systemd', 'Systemd'), ('System-V', 'System-V')], default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypackages',
            name='language',
            field=models.CharField(choices=[('C/C++', 'C/C++'), ('Golang', 'Golang')], default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ExtraMarco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('value', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.MyPackages')),
            ],
        ),
    ]
