# Generated by Django 2.2 on 2021-12-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20211222_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypackages',
            name='donwload_method',
            field=models.CharField(choices=[('git', 'git'), ('wget', 'wget'), ('local', 'local')], max_length=30),
        ),
        migrations.AlterField(
            model_name='mypackages',
            name='initial_method',
            field=models.CharField(choices=[('Systemd', 'Systemd'), ('System-V', 'System-V')], max_length=30),
        ),
        migrations.AlterField(
            model_name='mypackages',
            name='language',
            field=models.CharField(choices=[('C/C++', 'C/C++'), ('Golang', 'Golang')], max_length=30),
        ),
        migrations.AlterField(
            model_name='mypackages',
            name='type',
            field=models.CharField(choices=[('bbappend', 'bbappend'), ('bb', 'bb')], max_length=30),
        ),
    ]
