# Generated by Django 2.2 on 2021-12-23 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20211222_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypackages',
            name='license_default',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
