# Generated by Django 2.2 on 2021-12-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_mypackages_license_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypackages',
            name='license_default',
            field=models.CharField(choices=[('MIT', 'MIT'), ('Apache-2.0', 'Apache-2.0'), ('BSD', 'BSD'), ('GPL-1.0-only', 'GPL-1.0-only'), ('GPL-2.0-only', 'GPL-2.0-only'), ('GPL-3.0-only', 'GPL-3.0-only')], max_length=100),
        ),
    ]
