# Generated by Django 2.2 on 2021-12-23 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20211223_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypackages',
            name='systemd_auto_enable',
            field=models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypackages',
            name='systemd_service_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
