# Generated by Django 2.2 on 2021-12-26 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20211223_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=300)),
                ('base', models.CharField(choices=[('imx6ull-minimal', 'imx6ull-minimal'), ('raspberryPi-4B', 'raspberryPi-4B'), ('brand-new', 'brand-new')], max_length=60)),
                ('uboot', models.CharField(max_length=60)),
                ('kernel', models.CharField(max_length=60)),
                ('flash', models.CharField(max_length=60)),
                ('filesystem', models.CharField(max_length=60)),
                ('initial_method', models.CharField(choices=[('Systemd', 'Systemd'), ('System-V', 'System-V')], max_length=30)),
                ('jffs2_eraseblock', models.CharField(max_length=30)),
                ('mkubifs_args', models.CharField(max_length=120)),
                ('ubinize_args', models.CharField(max_length=120)),
                ('mxsboot_nand_args', models.CharField(max_length=120)),
                ('machine_include', models.CharField(max_length=120)),
                ('distro_include', models.CharField(max_length=120)),
                ('kernel_dts', models.CharField(max_length=120)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='MachineExtraMarco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('value', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.MyMachine')),
            ],
        ),
    ]
