# Generated by Django 2.2 on 2021-12-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_machineextramarco_myimage_mymachine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymachine',
            name='flash',
            field=models.CharField(choices=[('Spi-Nor', 'Spi-Nor'), ('Rawnand', 'Rawnand'), ('EMMC', 'EMMC'), ('SDCard', 'SDCard')], max_length=60),
        ),
    ]
