# Generated by Django 2.2 on 2021-12-27 02:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20211226_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='extramarco',
            name='strength',
            field=models.CharField(choices=[('normal', 'normal'), ('weak', 'weak'), ('very weak', 'very weak'), ('append', 'append')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machineextramarco',
            name='strength',
            field=models.CharField(choices=[('normal', 'normal'), ('weak', 'weak'), ('very weak', 'very weak'), ('append', 'append')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymachine',
            name='kernel_defconfig',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymachine',
            name='uboot_defconfig',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
