# Generated by Django 2.2 on 2021-12-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20211227_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymachine',
            name='base',
            field=models.CharField(choices=[('imx6ull', 'imx6ull'), ('raspberryPi-4B', 'raspberryPi-4B'), ('brand-new', 'brand-new')], max_length=60),
        ),
    ]
