# Generated by Django 2.2 on 2021-12-27 03:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20211227_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymachine',
            name='machine_include',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=60), size=None),
        ),
    ]
