# Generated by Django 2.2 on 2021-12-27 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20211227_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('base', models.CharField(choices=[('poky-minimal', 'poky-minimal'), ('poky-base', 'poky-base')], max_length=60)),
                ('machine_id', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=300)),
                ('wic_file', models.CharField(max_length=60)),
                ('uboot_name', models.CharField(max_length=30)),
                ('uboot_start', models.CharField(max_length=30)),
                ('uboot_end', models.CharField(max_length=30)),
                ('kernel_name', models.CharField(max_length=30)),
                ('kernel_start', models.CharField(max_length=30)),
                ('kernel_end', models.CharField(max_length=30)),
                ('fs_name', models.CharField(max_length=30)),
                ('fs_start', models.CharField(max_length=30)),
                ('fs_end', models.CharField(max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
