# Generated by Django 2.2 on 2021-12-28 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_myimage_myimagepackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyImagePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=60)),
                ('version', models.CharField(max_length=60)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.MyImage')),
            ],
        ),
    ]
