# Generated by Django 2.2 on 2021-12-28 09:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20211228_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymachine',
            name='distro_include',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=60), size=None),
        ),
        migrations.AlterField(
            model_name='mymachine',
            name='flash',
            field=models.CharField(choices=[('Spi-Nor', 'Spi-Nor'), ('Rawnand', 'Rawnand'), ('SDCard', 'SDCard')], max_length=60),
        ),
    ]
