# Generated by Django 2.2 on 2021-12-28 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20211228_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymachine',
            name='distro_version',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymachine',
            name='machineoverrides',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mymachine',
            name='base',
            field=models.CharField(choices=[('mx6:mx6ull:', 'imx6ull'), ('raspberrypi4', 'Raspberrypi4'), ('none', 'None')], max_length=60),
        ),
    ]
