# Generated by Django 2.2 on 2021-12-29 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20211228_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='metalayer',
            name='remote_or_local',
            field=models.CharField(choices=[('local', 'local'), ('remote', 'remote')], default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metalayer',
            name='sub',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mymachine',
            name='base',
            field=models.CharField(choices=[('imx6ull', 'imx6ull'), ('none', 'None')], max_length=60),
        ),
    ]
