# Generated by Django 2.2 on 2021-12-29 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20211229_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myimage',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='myimage',
            name='max_parallel_threads',
        ),
        migrations.RemoveField(
            model_name='myimage',
            name='parallel_make',
        ),
        migrations.AddField(
            model_name='myimage',
            name='flash',
            field=models.CharField(choices=[('Spi-Nor', 'Spi-Nor'), ('Rawnand', 'Rawnand'), ('SDCard', 'SDCard')], default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myimage',
            name='wic_file',
            field=models.CharField(max_length=120),
        ),
    ]
