version: "3"

volumes:
  postgres: {}
  redis: {}

services:
  web:
    build:
      context: .
      dockerfile: docker/files/django/Dockerfile_with_Mirror
    image: dianshao-web:latest
    container_name: dianshao-web
    env_file:
      - ./.envs/.django_with_host
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    network_mode: host

  yocto:
    build:
      context: .
      dockerfile: docker/files/yocto_celery/Dockerfile_with_Mirror
    image: dianshao-yocto:latest
    command: celery -A dianshao worker --loglevel=info --concurrency=1
    env_file:
      - ./.envs/.yocto_celery_with_host
    container_name: dianshao-yocto
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    volumes:
      - ${DIANSHAO_YOCTO_PROJECT_PATH}:/home/dianshao/yocto
    network_mode: host