# Generated by Django 2.2 on 2022-01-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymachine',
            name='distro_version',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='mymachine',
            name='filesystem',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='mymachine',
            name='jffs2_eraseblock',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='mymachine',
            name='kernel',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='mymachine',
            name='kernel_defconfig',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='mymachine',
            name='kernel_dts',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='mymachine',
            name='machineoverrides',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='mymachine',
            name='mkubifs_args',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='mymachine',
            name='mxsboot_nand_args',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='mymachine',
            name='ubinize_args',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='mymachine',
            name='uboot',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='mymachine',
            name='uboot_defconfig',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
