# Generated by Django 2.2 on 2022-01-11 08:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20220111_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymachine',
            name='distro_include',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='mymachine',
            name='machine_include',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, size=None),
        ),
    ]
