# Generated by Django 2.2 on 2022-01-11 09:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20220111_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymachine',
            name='distro_include',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=60), size=None),
        ),
        migrations.AlterField(
            model_name='mymachine',
            name='machine_include',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=60), size=None),
        ),
    ]
