# Generated by Django 2.2 on 2022-01-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20220111_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localfile',
            name='content',
            field=models.CharField(max_length=20000),
        ),
    ]
