# Generated by Django 2.2 on 2022-01-17 01:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20220115_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypackages',
            name='config_file_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
