# Generated by Django 2.2 on 2022-01-17 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_mypackages_go_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypackages',
            name='source_directory',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
