# Generated by Django 2.2 on 2022-01-22 08:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_mypackages_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='myimage',
            name='packages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=60), default='{}', size=None),
            preserve_default=False,
        ),
    ]
