# Generated by Django 2.2 on 2022-01-22 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_myimage_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyImageExtraMarco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('value', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('strength', models.CharField(choices=[('normal', 'normal'), ('weak', 'weak'), ('very weak', 'very weak'), ('append', 'append')], max_length=100)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.MyImage')),
            ],
        ),
    ]
