# Generated by Django 2.2 on 2022-01-23 01:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_myimageextramarco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypackages',
            name='go_proxy',
        ),
        migrations.AddField(
            model_name='mypackages',
            name='go_env',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=120), default='{}', size=None),
            preserve_default=False,
        ),
    ]
