# Generated by Django 2.2 on 2022-01-23 01:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20220123_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypackages',
            name='files_pn',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=120), default='{}', size=None),
            preserve_default=False,
        ),
    ]
